version: '3.8'

services:
  # Redis for caching and BullMQ
  valkey:
    image: docker.io/bitnami/valkey:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - valkey-data:/bitnami/valkey/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-h', 'localhost', '-p', '6379', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: autumn-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: autumn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: autumn_dev_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  valkey-data:
  postgres-data:

networks:
  autumn-network: